name: Scrape eBay Tech Deals

on:
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours
  workflow_dispatch:        # Allows manual triggering

jobs:
  scrape-ebay-tech-deals:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install selenium pandas webdriver-manager fake-useragent

      - name: Run Selenium scraper
        run: python scraper.py

      - name: Commit and Push updated CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ebay_tech_deals.csv  # Corrected CSV filename
          git commit -m "Updated eBay Tech Deals data (3-hour intervals)"
           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        
